name: Lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Restore dotnet tools
        run: dotnet tool restore
      - name: Restore Paket
        run: dotnet paket restore
      - name: Check code format
        run: dotnet fake build -t lint
