name: Test

on: push

jobs:
  test:
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Restore dotnet tools
        run: dotnet tool restore
      - name: Restore Paket
        run: dotnet paket restore
      - name: Run tests
        run: dotnet fake build -t test
